const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({ status: 'healthy', uptime: process.uptime() }));
app.get('/', (req, res) => res.json({ message: '🍋 Dream Nutz API is running!' }));
app.listen(PORT, () => console.log(`🚀 Dream Nutz running on http://localhost:${PORT}`));
